In [22]:
import talib
import numpy as np

In [2]:
c = numpy.random.randn(100)

In [3]:
k, d = talib.STOCHRSI(c)

In [4]:
talib.SMA(c)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,  0.23806675,
        0.25118026,  0.21570465,  0.14731505,  0.02920236, -0.02287424,
       -0.04117223, -0.0331891 , -0.03179004, -0.1007759 , -0.12120333,
       -0.10063583, -0.08101063, -0.06533365, -0.10581352, -0.07390058,
       -0.00531541, -0.01792927, -0.04250513, -0.05405496, -0.06079714,
       -0.08257569, -0.09590963, -0.10139308, -0.12778663, -0.06882718,
       -0.16910431, -0.19504713, -0.20196815, -0.23362636, -0.16018206,
       -0.09983551, -0.09901366, -0.09283969, -0.01757848,  0.03529346,
        0.0353867 ,  0.00784478, -0.02568555,  0.0316819 ,  0.05

In [5]:
talib.RSI(c, 5)

array([        nan,         nan,         nan,         nan,         nan,
       64.06410519, 62.93375187, 52.31807457, 57.33960889, 49.76474094,
       56.88937888, 36.56736451, 45.43579852, 54.73429678, 35.74810883,
       41.26373157, 56.86455412, 56.04749156, 39.80470927, 57.90623181,
       46.12026823, 53.89653788, 45.22504941, 65.64929916, 54.5037458 ,
       65.02010555, 50.55302528, 41.06976604, 39.17978344, 28.44884316,
       51.25341382, 54.2399631 , 55.26314251, 39.230008  , 37.03407665,
       60.75295806, 66.17672532, 52.92941499, 37.57304482, 48.13546083,
       62.9451094 , 46.92067293, 51.36872803, 42.38783944, 47.20833053,
       61.7325655 , 48.73997034, 44.50629882, 36.08121121, 55.67297158,
       41.49928207, 51.29794553, 46.2086607 , 61.1314268 , 71.5322367 ,
       41.77853575, 48.76587745, 44.79382958, 37.79302457, 53.42416555,
       64.43419621, 51.07354599, 53.24324067, 58.68342492, 48.33306409,
       53.62989747, 51.80767832, 37.22141032, 52.29045075, 49.02

In [32]:
def get_rand():
    return 5 * np.random.random_sample(100) + 1

In [54]:
c_open = get_rand()
c_high = get_rand()
c_low = c_high - get_rand()
c_low[c_low < 0] = 0
c_close = get_rand()

In [60]:
talib.MACD(c_close)

(array([        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,  0.15647312,  0.28679177,
         0.17419649, -0.0526254 ,  0.13879113,  0.22619044,  0.29218358,
         0.33972781,  0.34523914,  0.12597348,  0.20522437, -0.04339001,
        -0.04410859, -0.04818746, -0.06884496, -0.22472241, -0.20900382,
        -0.03955136,  0.1007804 ,  0.18962043,  0.27960872,  0.39056567,
         0.44646522,  0.44766258,  0.4106279 ,  0.30978457,  0.26353657,
         0.14936283,  0.22600942,  0.01417017, -0.18438999, -0.19081215,
        -0.09093009, -0.05589379, -0.22014577, -0.2

In [56]:
talib.CDLHAMMER(c_open, c_high, c_low, c_close)

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0, 100,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 100,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=int32)

In [57]:
import plotly.graph_objects as go
import pandas as pd

In [58]:
df = pd.DataFrame()
df["Open"] = c_open
df["High"] = c_high
df["Low"] = c_low
df["Close"] = c_close
df

Open      High       Low     Close
0   4.689485  1.233235  0.000000  1.345421
1   3.677218  1.928612  0.000000  3.378189
2   4.020953  4.778371  1.286857  5.489807
3   1.909236  5.255578  1.225176  1.928092
4   1.538511  4.331764  1.947870  3.379261
..       ...       ...       ...       ...
95  1.785971  5.853463  1.728169  5.116885
96  5.094220  1.019869  0.000000  3.244661
97  2.876254  3.482290  1.452590  2.901395
98  4.570472  4.828540  0.183895  1.885486
99  4.894394  4.337832  0.632281  4.790728

[100 rows x 4 columns]

In [59]:
fig = go.Figure(data=go.Ohlc(x=df.index,
                             open=df['Open'],
                             high=df['High'],
                             low=df['Low'],
                             close=df['Close']))
  
# show the figure
fig.show()